[package]
name = "aip-api"
version.workspace = true
edition.workspace = true

[dependencies]
actix-cors.workspace = true
actix-multipart = "0.7.2"
actix-web.workspace = true
aip-charts = { path = "../charts" }
aip-domain = { path = "../domain" }
aip-navigation = { path = "../navigation" }
aip-weather = { path = "../weather" }
chrono.workspace = true
futures-util.workspace = true
rfd = "0.15"
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
serde_json.workspace = true
